### ISSUE TITLE
Implement orientation drivetrain methods for PID

### ISSUE THREAD

**Issue by SomewhatMay** [Arctos6135/frc-2024#8]
The `PIDSetAngle` command requires the following drivetrain methods:

`public double getYaw()` 
method that provides information about the current yaw of the current drivetrain. Could use gyros or encoders?

We should have a rotation PIDController in the Drivetrain that every command uses when it is needed to calculate a specific angle the drivetrain should face. This should be accessible through the `public PIDController getRotationController()` method (or something similar)

**Comment by n-arms** [comment]
Oop, I may have accidentally done this while getting PIDSetAngle to compile. I'm marking as resolved because I think rather than having controllers for rotation and translation like we did last lear, we want to use PID + feedforward to command each side of the drivetrain to a specific speed, and then do the math from there (see #4)
